// Customer
export const CUSTOMER_LOADED = 'CUSTOMER_LOADED';
export const CUSTOMER_STATUS_TOGGLE = 'CUSTOMER_STATUS_TOGGLE';

// Addresses
export const ADDRESS_LOADED = 'ADDRESS_LOADED';
export const ADDRESS_DELETED = 'ADDRESS_DELETED';

// Phone numbers
export const PHONE_NUMBER_LOADED = 'PHONE_NUMBER_LOADED';
export const PHONE_NUMBER_DELETED = 'PHONE_NUMBER_DELETED';


// Email address
export const EMAIL_ADDRESS_LOADED = 'EMAIL_ADDRESS_LOADED';
export const EMAIL_ADDRESS_DELETED = 'EMAIL_ADDRESS_DELETED';
